-- Calibration tables (R1, FR-30.1).
--
-- Generated by Drizzle Kit, then made re-runnable by hand: the runner retries
-- an interrupted file from the top, so every statement here carries IF NOT
-- EXISTS (AGENTS.md rule 9).
CREATE TABLE IF NOT EXISTS `calibration_points` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`calibration_id` integer NOT NULL,
	`feature` text NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`image_u` real NOT NULL,
	`image_v` real NOT NULL,
	`x_m` real NOT NULL,
	`y_m` real NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`calibration_id`) REFERENCES `calibrations`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `calibration_points_calibration_idx` ON `calibration_points` (`calibration_id`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `calibrations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`video_id` integer NOT NULL,
	`from_ms` integer DEFAULT 0 NOT NULL,
	`pitch_length_m` real DEFAULT 105 NOT NULL,
	`pitch_width_m` real DEFAULT 68 NOT NULL,
	`rms_error_px` real DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`video_id`) REFERENCES `videos`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `calibrations_video_from_unique` ON `calibrations` (`video_id`,`from_ms`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `calibrations_video_idx` ON `calibrations` (`video_id`);