-- Player positions (R1, FR-30.3).
--
-- Generated by Drizzle Kit, then made re-runnable by hand: the runner retries
-- an interrupted file from the top, so every statement carries IF NOT EXISTS
-- (AGENTS.md rule 9).
CREATE TABLE IF NOT EXISTS `positions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`uid` text NOT NULL,
	`event_id` integer NOT NULL,
	`player_id` integer NOT NULL,
	`team_id` integer NOT NULL,
	`calibration_id` integer,
	`image_u` real NOT NULL,
	`image_v` real NOT NULL,
	`x_m` real NOT NULL,
	`y_m` real NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`team_id`) REFERENCES `teams`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`calibration_id`) REFERENCES `calibrations`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `positions_uid_unique` ON `positions` (`uid`);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `positions_event_player_unique` ON `positions` (`event_id`,`player_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `positions_event_idx` ON `positions` (`event_id`);