-- Phases: a tag that runs, and the actions recorded inside it (R2, FR-55).
--
-- Generated by Drizzle Kit, then made re-runnable by hand: the runner retries an
-- interrupted file from the top, so every statement carries IF NOT EXISTS
-- (AGENTS.md rule 9). Three tables and no new columns — a column cannot be added
-- re-runnably, which is why ADR 0012 keeps every new fact in a table.
CREATE TABLE IF NOT EXISTS `phase_tags` (
	`tag_id` integer PRIMARY KEY NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `event_parents` (
	`child_id` integer NOT NULL,
	`parent_id` integer NOT NULL,
	PRIMARY KEY(`child_id`, `parent_id`),
	FOREIGN KEY (`child_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`parent_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `event_parents_parent_idx` ON `event_parents` (`parent_id`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `phase_sessions` (
	`event_id` integer PRIMARY KEY NOT NULL,
	`stream_key` text NOT NULL,
	`opened_at_ms` integer NOT NULL,
	`last_seen_ms` integer NOT NULL,
	`closed_by` text,
	FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `phase_sessions_open_stream_unique` ON `phase_sessions` (`stream_key`) WHERE "phase_sessions"."closed_by" IS NULL;
