-- A drawing's own time on screen (R2, FR-20.16).
--
-- Generated by Drizzle Kit, then made re-runnable by hand: the runner retries an
-- interrupted file from the top, so the statement carries IF NOT EXISTS
-- (AGENTS.md rule 9). One table and no new column, because a pair of times does
-- not fit the single `window_ms` column and a column cannot be added re-runnably
-- (ADR 0008) — the same answer the phase tables use.
CREATE TABLE IF NOT EXISTS `annotation_windows` (
	`annotation_id` integer PRIMARY KEY NOT NULL,
	`start_ms` integer NOT NULL,
	`end_ms` integer NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`annotation_id`) REFERENCES `annotations`(`id`) ON UPDATE no action ON DELETE cascade
);
